name: Build and Test .NET Application
description: Common action to build and test the SeatFair .NET API

inputs:
  dotnet-version:
    description: ".NET version to use"
    required: false
    default: "9.0.x"

runs:
  using: composite
  steps:
    - name: ⚙️ Set up .NET
      id: setup_dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: ♻️ Cache NuGet packages and dotnet tools
      id: cache_nuget_packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.nuget/packages
          ~/.nuget/toolcache
        key: ${{ runner.os }}-dotnet-${{ hashFiles('**/packages.lock.json', '**/packages.config', '**/*.csproj', '**/.config/dotnet-tools.json') }}
        restore-keys: |
          ${{ runner.os }}-dotnet-

    - name: ⚙️ Restore tools
      id: restore_tools
      shell: bash
      run: |
        make check-tools
